name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
   - cron: "7 4 19 * *"

permissions:
  contents: read

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        # These version names ensure that new Node versions are automatically tested,
        # but also ensures that the oldest supported version is changed on purpose.
        node-version: [lts/*]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - node-version: latest
            os: ubuntu-latest
          - node-version: lts/-1
            os: ubuntu-latest
          - node-version: 18.11.0
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install-clean

      - name: Test code
        run: npm test
